name: Axons

channels:
  - conda-forge
    
dependencies:
  - python=3.9
  - pyqt=5.12.*
  - numpy
  - scipy
  - scikit-image
  - matplotlib-base
  - joblib
  - napari
  - pip
  - pip:
    - pystackreg